POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "Admin",
    "password": "1234567890"
}

###

GET http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NDI0OTc2LCJpYXQiOjE3MzY0MjQ2NzYsImp0aSI6IjZmMzBiN2YxYzY4ODQ1N2U5NGJmMDdhNTZhYmFhMWE5IiwidXNlcl9pZCI6MX0.Ntj27TEcPnGi0PS_Px6kNfEiKzP58ZmpYcftj1FreEA
